import { gql } from '@apollo/client';
import Page from '@components/Page';
import client from '@src/apollo-client';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Blog({ content }) {
  // const t = useTranslations('index');
  // const { home } = content;
  const { locale } = useRouter();
  console.log(content);

  return (
    <div>
      <Head>
        <title>Rohald.dev | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="alternate" hrefLang={locale} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <h1>Blog</h1>
        <div className="blogposts">
          {content.blog.map(post => (
            <div key={post.id} className="blogpost">
              <h2>{post.title}</h2>
              <Link href="/blog/[slug]" as={`/blog/${post.slug}`}>
                <a>Read more</a>
              </Link>
            </div>
          ))}
        </div>
      </Page>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  const data = await client.query({
    query: gql`
      query GetAllBlogPosts {
        blogposts {
          id
          title
          slug
        }
      }
    `,
  });

  //   let home = data.data.page;
  //   if (home.localizations.length) {
  //     home = {
  //       ...home,
  //       ...home.localizations[0],
  //     };
  //   }

  return {
    props: {
      messages: (await import(`../../locales/${locale}.json`)).default,
      content: {
        blog: data.data.blogposts,
      },
    },
  };
}
