import Head from 'next/head';
import { useTranslations } from 'next-intl';
// import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export default function Home() {
  const t = useTranslations('index');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>From next-intl</h2>
      <h1>{t('heading')}</h1>
      <p>{t('content')}</p>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      content: {
        ...require(`../locales/${locale}.json`),
      },
    },
  };
  // const client = new ApolloClient({
  //   uri: process.env.API_ENDPOINT,
  //   cache: new InMemoryCache(),
  // });

  // const data = await client.query({
  //   query: gql`
  //     query HomePage {
  //       page(where: { slug: "home" }) {
  //         id
  //         heroLink
  //         heroText
  //         heroTitle
  //         name
  //         slug
  //         heroBackground {
  //           url
  //           width
  //           height
  //         }
  //       }
  //     }
  //   `,
  // });

  // console.log(data);
  // const home = data.data.page;
  // return {
  //   props: { home },
  // };
}
